import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import test from 'node:test';
import { LiveActivityStore } from '../server/live-activity.js';
import { STATION_BOARD_LINES, londonLocal, londonClock, selectEvents, mergeContexts } from '../server/station-board-v2.js';

test('actual local HTTP endpoint preserves v1 and negotiates all19 v2 boards with no public cache access', { timeout: 15000 }, async (t) => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'tb-v2-http-'));
  const child = spawn(process.execPath, ['server/index.js'], { cwd: new URL('..', import.meta.url), env: { PATH: process.env.PATH, PORT: '0', LIVE_ACTIVITY_WORKER_ENABLED: 'false', DISRUPTION_ALERT_WORKER_ENABLED: 'false', TUBEBOARD_STATUS_MONITOR_ENABLED: 'false', LIVE_ACTIVITY_DATA_FILE: path.join(directory, 'activities.json'), DISRUPTION_ALERT_DATA_FILE: path.join(directory, 'alerts.json') }, stdio: ['ignore', 'pipe', 'pipe'] });
  t.after(async () => { child.kill('SIGTERM'); await once(child, 'exit'); await fs.rm(directory, { recursive: true, force: true }); });
  const origin = await new Promise((resolve, reject) => { child.once('error', reject); let output = ''; child.stdout.on('data', (data) => { output += data; const match = /http:\/\/localhost:(\d+)/.exec(output); if (match) resolve(match[0]); }); child.once('exit', () => reject(new Error('Local service ended before listen'))); });
  const fixture = JSON.parse(await fs.readFile(new URL('../contracts/fixtures/live-activity-registration-v1.json', import.meta.url)));
  const health = await (await fetch(`${origin}/healthz`)).json(); assert.equal(health.ok, true); assert.equal(health.contractVersion, 1); assert.deepEqual(health.contentStateContracts, ['station-board-v2']);
  const post = async (body) => fetch(`${origin}/api/live-activities/tokens`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const legacyResponse = await post(fixture); assert.equal(legacyResponse.status, 200); assert.deepEqual(await legacyResponse.json(), { ok: true });
  const schemaResponse = await fetch(`${origin}/contracts/live-activity-registration-v2.schema.json`); assert.equal(schemaResponse.status, 200); const schema = await schemaResponse.json(); assert.equal(schema.properties.lineID.enum.length, 19); assert.equal(schema.properties.contentStateContract.const, 'station-board-v2');
  for (const [lineID, line] of STATION_BOARD_LINES) { const response = await post({ ...fixture, installID: `synthetic-${lineID}`, activityID: `synthetic-${lineID}`, stationID: line.boundedOriginID, lineID, contentStateContract: 'station-board-v2' }); assert.equal(response.status, 200, lineID); }
  assert.equal((await post({ ...fixture, installID: 'synthetic-invalid', lineID: 'dlr' })).status, 400);
  assert.equal((await post({ ...fixture, installID: 'synthetic-invalid', contentStateContract: 'station-board-v9' })).status, 400);
  assert.equal((await post({ ...fixture, installID: 'synthetic-invalid', contentStateContract: 'station-board-v2', lineID: 'mildmay' })).status, 400);
  assert.equal((await fetch(`${origin}/contracts/station-board-catalogue-v2.json`)).status, 404);
  assert.equal((await fetch(`${origin}/server/station-board-v2.js`)).status, 404);
  const anchor = Date.now(), local = londonLocal(anchor), day = local.slice(0, 10), minute = Number(local.slice(11, 13)) * 60 + Number(local.slice(14, 16)) + 1;
  assert.ok(minute < 1440, 'Endpoint carry-forward replay needs a current-day minute remaining');
  const departure = londonClock(`${day}T${String(Math.floor(minute / 60)).padStart(2, '0')}:${String(minute % 60).padStart(2, '0')}:00`), midnight = londonClock(`${new Date(Date.parse(`${day}T12:00:00Z`) + 86400000).toISOString().slice(0, 10)}T00:00:00`);
  const board = { ...fixture, installID: 'synthetic-seed-install', activityID: 'synthetic-seed-activity', stationID: '940GZZLUEGW', lineID: 'northern', selectionMode: 'allPlatforms', platformID: null, platformHeading: null, platformLabel: null, platformDirection: null, tokenUpdatedAt: new Date(anchor).toISOString(), contentStateContract: 'station-board-v2' };
  const publication = { url: 'https://tfl.gov.uk/tfl/syndication/feeds/journey-planner-timetables.zip', sha256: 'a'.repeat(64), timezone: 'Europe/London', operatingStartDate: `${day.slice(0,4)}-01-01`, operatingEndDate: `${day.slice(0,4)}-12-31`, holidayCoverageStart: `${day.slice(0,4)}-01-01`, holidayCoverageEnd: `${day.slice(0,4)}-12-31`, nonOperationBankHolidays: true };
  const seed = { schemaVersion: 1, stationID: board.stationID, lineID: board.lineID, contexts: [{ sourceID: 'timetable', observedAt: new Date(anchor).toISOString(), expiresAt: new Date(Math.min(anchor + 600000, midnight)).toISOString(), publication, rows: [0,1,2].map((i) => ({ id: `schedule:northern:${board.stationID}:${day}:0:0:${i}`, destinationID: '940GZZLUMDN', destination: 'Morden', departure: new Date(departure).toISOString(), via: i === 1 ? 'Bank' : null, routeStationIDs: i === 1 ? ['940GZZLUBNK', '940GZZLUMDN'] : ['940GZZLUMDN'], serviceDay: day, profileName: 'Endpoint fixture profile', profileSHA256: 'b'.repeat(64), weekdays: [new Date(`${day}T12:00:00Z`).getUTCDay() + 1], serviceMinute: minute, isBankHoliday: false })) }] };
  const seededResponse = await post({ ...board, plannedContextSeed: seed }); assert.equal(seededResponse.status, 200); assert.equal((await seededResponse.json()).contentStateContract, 'station-board-v2');
  const seededStore = new LiveActivityStore(path.join(directory, 'activities.json')); await seededStore.load();
  const seeded = seededStore.state.records.find((r) => r.activityID === board.activityID);
  assert.equal(seeded.stationBoardCache.sources.timetable.events.length, 3);
  const planner = { stationID: board.stationID, lineID: board.lineID, sourceID: 'journey-planner', id: 'one-bounded-planner', kind: 'outgoingDeparture', timeEvidence: 'scheduledDeparture', destination: 'Morden', destinationStationID: '940GZZLUMDN', time: departure, platform: null, receivedAt: anchor + 1000, expiresAt: Math.min(anchor + 121000, midnight) };
  const partial = await seededStore.retainStationBoard(board.activityID, board.environment, { sources: { 'journey-planner': { observedAt: anchor + 1000, events: [planner] } } }, new Date(anchor + 1000));
  assert.equal(selectEvents(partial, board, anchor + 1000).length, 3);
  const marker = { stationID: board.stationID, lineID: board.lineID, reason: 'publicationChanged', observedAt: anchor + 2000 };
  const rejected = await seededStore.retainStationBoard(board.activityID, board.environment, { rejections: [marker] }, new Date(anchor + 2000));
  assert.equal(rejected.sources.timetable, undefined);
  await seededStore.upsertToken({ ...board, plannedContextSeed: seed }, new Date(anchor + 3000));
  assert.equal(seededStore.state.records.find((r) => r.activityID === board.activityID).stationBoardCache.sources.timetable, undefined);
  const expiry = mergeContexts(partial, {}, board, Math.min(anchor + 600000, midnight)); assert.equal(expiry.sources.timetable, undefined);
  const bad = structuredClone(seed); bad.contexts[0].rows[0].platform = 'Platform 1'; assert.equal((await post({ ...board, plannedContextSeed: bad })).status, 400);
  const saved = JSON.parse(await fs.readFile(path.join(directory, 'activities.json'))); assert.equal(saved.records.filter((r) => r.contentStateContract === 'station-board-v2').length, 20); assert.equal(saved.records.find((r) => r.activityID === fixture.activityID).contentStateContract, undefined);
});
